artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/fiftybucks101/Datasets/raw/main/wine_quality_dataset.zip
  local_data_file: artifacts/data_ingestion/wine_quality.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  unziped_data_dir: artifacts/data_ingestion/wine_quality_dataset/WineQT.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/wine_quality_dataset/WineQT.csv

model_trainer:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_training/model.joblib
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  train_metrics_file: train_mertics.json
  test_metrics_file: test_mertics.json
  model_name: model.joblib
  




  
